sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hWdzFo6Ywjl/81Raj2MOgzNRgDXjjJi67vkygImiRxAytNC65GfeXvn/ewHWeqed0nurahwT7vwai36oly5rSw+Xtr9OBbr6TqT3VB1KX1uDHuJ3Hb25b9NxhKCe4fo464pkPnpitKrfuNY21/lbuEAwbDSa+mLQsXIPH9Vz6HdaiczLQG33ghLtAAS4K10+aNpylyfUpD3UrFEU5szBN8RguBZx/NLXf7c9ZNxbdLXDh8nI2F/m+FhHVpx5XqDNhqdz23mMp2C6lLQHwu/AADhcL3bAPtxbXpTIhNjjg9su0qMLAn3AREBkNEO3VlwEJGB+6MPyGsxtakgOfYMkTONqwjRxiuOb5DMR18NcPhG75ImJKTH3DD+O3SCim+VZ9RDnjdM+0szeoEU9Zr+iuDsA4e49B4MxYAHsU2eCkse74IRDVwRGsU1T1xLvumJcbjtr0LdwXKKGySPCcO5H7eyRE5qSg/mKK+r5zmzjp70CgLgHhLuYxY+M7LC/BW0oQtYfvtXnQzlvkJvqsfK1ys6X9KXwyQfFTY9XbL0HRwmpSIQZfwn9wv8MWxlAb/n1NW8vNpGgubStGdeWqxJaElEQnerhJn33gseVPVx2H1SJfuCPQoUSIlD6DnTR65ujfS007N4Gb8N5uO7VRq2qPmelpxbIecmhTaILsZkRDcc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/North-America---Volume-1_1865
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy